//  Phaser.Actions

module.exports = {

    Angle: require('./Angle'),
    Call: require('./Call'),
    GridAlign: require('./GridAlign'),
    IncAlpha: require('./IncAlpha'),
    IncX: require('./IncX'),
    IncXY: require('./IncXY'),
    IncY: require('./IncY'),
    PlaceOnCircle: require('./PlaceOnCircle'),
    PlaceOnLine: require('./PlaceOnLine'),
    PlaceOnRectangle: require('./PlaceOnRectangle'),
    PlaceOnTriangle: require('./PlaceOnTriangle'),
    PlayAnimation: require('./PlayAnimation'),
    RandomCircle: require('./RandomCircle'),
    RandomEllipse: require('./RandomEllipse'),
    RandomLine: require('./RandomLine'),
    RandomRectangle: require('./RandomRectangle'),
    RandomTriangle: require('./RandomTriangle'),
    Rotate: require('./Rotate'),
    RotateAround: require('./RotateAround'),
    RotateAroundDistance: require('./RotateAroundDistance'),
    ScaleX: require('./ScaleX'),
    ScaleXY: require('./ScaleXY'),
    ScaleY: require('./ScaleY'),
    SetAlpha: require('./SetAlpha'),
    SetOrigin: require('./SetOrigin'),
    SetRotation: require('./SetRotation'),
    SetScale: require('./SetScale'),
    SetScaleX: require('./SetScaleX'),
    SetScaleY: require('./SetScaleY'),
    SetVisible: require('./SetVisible'),
    SetX: require('./SetX'),
    SetXY: require('./SetXY'),
    SetY: require('./SetY'),
    SmootherStep: require('./SmootherStep'),
    SmoothStep: require('./SmoothStep'),
    Spread: require('./Spread'),
    ToggleVisible: require('./ToggleVisible')

};
