/**
 * @author       Richard Davey <rich@photonstorm.com>
 * @copyright    2019 Photon Storm Ltd.
 * @license      {@link https://github.com/photonstorm/phaser/blob/master/license.txt|MIT License}
 */

/**
 * @namespace Phaser.Animations.Events
 */

module.exports = {

    ADD_ANIMATION: require('./ADD_ANIMATION_EVENT'),
    ANIMATION_COMPLETE: require('./ANIMATION_COMPLETE_EVENT'),
    ANIMATION_REPEAT: require('./ANIMATION_REPEAT_EVENT'),
    ANIMATION_RESTART: require('./ANIMATION_RESTART_EVENT'),
    ANIMATION_START: require('./ANIMATION_START_EVENT'),
    PAUSE_ALL: require('./PAUSE_ALL_EVENT'),
    REMOVE_ANIMATION: require('./REMOVE_ANIMATION_EVENT'),
    RESUME_ALL: require('./RESUME_ALL_EVENT'),
    SPRITE_ANIMATION_COMPLETE: require('./SPRITE_ANIMATION_COMPLETE_EVENT'),
    SPRITE_ANIMATION_KEY_COMPLETE: require('./SPRITE_ANIMATION_KEY_COMPLETE_EVENT'),
    SPRITE_ANIMATION_KEY_REPEAT: require('./SPRITE_ANIMATION_KEY_REPEAT_EVENT'),
    SPRITE_ANIMATION_KEY_RESTART: require('./SPRITE_ANIMATION_KEY_RESTART_EVENT'),
    SPRITE_ANIMATION_KEY_START: require('./SPRITE_ANIMATION_KEY_START_EVENT'),
    SPRITE_ANIMATION_KEY_UPDATE: require('./SPRITE_ANIMATION_KEY_UPDATE_EVENT'),
    SPRITE_ANIMATION_REPEAT: require('./SPRITE_ANIMATION_REPEAT_EVENT'),
    SPRITE_ANIMATION_RESTART: require('./SPRITE_ANIMATION_RESTART_EVENT'),
    SPRITE_ANIMATION_START: require('./SPRITE_ANIMATION_START_EVENT'),
    SPRITE_ANIMATION_UPDATE: require('./SPRITE_ANIMATION_UPDATE_EVENT')

};
