export declare const VERSION = "3.0.0";
export declare const AUTO = 0;
export declare const CANVAS = 1;
export declare const WEBGL = 2;
export declare const CONTAINER = 99;
export declare const IMAGE = 20;
export declare const state: {
    PENDING: number;
    INSTALLED: number;
    BOOT: number;
    INIT: number;
    PRELOAD: number;
    CREATE: number;
    UPDATE: number;
    RENDER: number;
    SHUTDOWN: number;
};
export declare const blendModes: {
    NORMAL: number;
    ADD: number;
    MULTIPLY: number;
    SCREEN: number;
    OVERLAY: number;
    DARKEN: number;
    LIGHTEN: number;
    COLOR_DODGE: number;
    COLOR_BURN: number;
    HARD_LIGHT: number;
    SOFT_LIGHT: number;
    DIFFERENCE: number;
    EXCLUSION: number;
    HUE: number;
    SATURATION: number;
    COLOR: number;
    LUMINOSITY: number;
};
export declare const scaleModes: {
    DEFAULT: number;
    LINEAR: number;
    NEAREST: number;
};
