module.exports = {

    Add: require('./Add'),
    Boot: require('./Boot'),
    BootScene: require('./BootScene'),
    BringToTop: require('./BringToTop'),
    Create: require('./Create'),
    CreateSceneDisplay: require('./CreateSceneDisplay'),
    CreateSceneFromFunction: require('./CreateSceneFromFunction'),
    CreateSceneFromInstance: require('./CreateSceneFromInstance'),
    CreateSceneFromObject: require('./CreateSceneFromObject'),
    GetActiveScene: require('./GetActiveScene'),
    GetActiveSceneIndex: require('./GetActiveSceneIndex'),
    GetActiveSceneIndexByKey: require('./GetActiveSceneIndexByKey'),
    GetKey: require('./GetKey'),
    GetScene: require('./GetScene'),
    GetSceneAt: require('./GetSceneAt'),
    GetSceneIndex: require('./GetSceneIndex'),
    GetSceneIndexByKey: require('./GetSceneIndexByKey'),
    IsActive: require('./IsActive'),
    IsSleeping: require('./IsSleeping'),
    LoadComplete: require('./LoadComplete'),
    MoveDown: require('./MoveDown'),
    MoveUp: require('./MoveUp'),
    Pause: require('./Pause'),
    PayloadComplete: require('./PayloadComplete'),
    Resume: require('./Resume'),
    SendToBack: require('./SendToBack'),
    SetupCallbacks: require('./SetupCallbacks'),
    Sleep: require('./Sleep'),
    SortScenes: require('./SortScenes'),
    Start: require('./Start'),
    Stop: require('./Stop'),
    Swap: require('./Swap'),
    SwapPosition: require('./SwapPosition'),
    Wake: require('./Wake')

};
