module.exports = [
    'uniform mat4 u_view_matrix;',
    'attribute vec2 a_position;',
    'attribute vec2 a_tex_coord;',
    'attribute float transform_a;',
    'attribute float transform_b;',
    'attribute float transform_c;',
    'attribute float transform_d;',
    'attribute vec2 transform_t;',
    'attribute vec3 a_color;',
    'varying vec2 v_tex_coord;',
    'varying vec3 v_color;',
    'void main () {',
    '   vec2 t_position;',
    '   t_position.x = a_position.x * transform_a + a_position.y * transform_c;',
    '   t_position.y = a_position.x * transform_b + a_position.y * transform_d;',
    '   gl_Position = u_view_matrix * vec4(t_position + transform_t, 1.0, 1.0);',
    '   v_tex_coord = a_tex_coord;',
    '   v_color = a_color;',
    '}'
].join('\n');
