module.exports = [
    'vec4 applyAlphaDiscard(vec4 fragColor)',
    '{',
    '    #ifdef ALPHA_DISCARD_STRATEGY_THRESHOLD',
    '    if (fragColor.a < ALPHA_DISCARD_STRATEGY_THRESHOLD)',
    '    {',
    '        discard;',
    '    }',
    '    #endif',
    '    #ifdef ALPHA_DISCARD_STRATEGY_DITHER',
    '    float noise = fract(52.9829189 * fract(0.06711056 * gl_FragCoord.x + 0.00583715 * gl_FragCoord.y));',
    '    if (noise >= fragColor.a)',
    '    {',
    '        discard;',
    '    }',
    '    #endif',
    '    return fragColor / fragColor.a;',
    '}',
].join('\n');
