module.exports = [
    '#define SHADER_NAME PHASER_BITMAP_MASK_FS',
    '',
    'precision mediump float;',
    '',
    'uniform vec2 uResolution;',
    'uniform sampler2D uMainSampler;',
    'uniform sampler2D uMaskSampler;',
    'uniform bool uInvertMaskAlpha;',
    '',
    'void main ()',
    '{',
    '    vec2 uv = gl_FragCoord.xy / uResolution;',
    '',
    '    vec4 mainColor = texture2D(uMainSampler, uv);',
    '    vec4 maskColor = texture2D(uMaskSampler, uv);',
    '',
    '    // float alpha = maskColor.a;',
    '',
    '    // float alpha = (1.0 - maskColor.a);',
    '    // float alpha = (1.0 - maskColor.a) * mainColor.a;',
    '    // alpha *= maskColor.a;',
    '    // float alpha = maskColor.a;',
    '',
    '    if (!uInvertMaskAlpha)',
    '    {',
    '        mainColor *= maskColor.a;',
    '',
    '        // alpha *= (maskColor.a);',
    '    }',
    '    else',
    '    {',
    '        mainColor *= (1.0 - maskColor.a);',
    '',
    '        // alpha *= (1.0 - maskColor.a);',
    '    }',
    '',
    '    // gl_FragColor = vec4(mainColor.rgb, alpha);',
    '',
    '    // gl_FragColor = vec4(mainColor.rgb, mainColor.a) * (1.0 - maskColor.a);',
    '',
    '    gl_FragColor = mainColor;',
    '',
    '    // gl_FragColor = vec4(mainColor.rgb * alpha, 0.0);',
    '}',
    ''
].join('\n');
