module.exports = [
    '#define SHADER_NAME CIRCLE_FS',
    'precision mediump float;',
    'uniform sampler2D uMainSampler;',
    'uniform vec2 resolution;',
    'uniform vec3 color;',
    'uniform vec4 backgroundColor;',
    'uniform float width;',
    'varying vec2 outTexCoord;',
    'float circle (in vec2 _st, in float _radius)',
    '{',
    '    vec2 dist = _st - vec2(0.5);',
    '	return 1.0 - smoothstep(_radius - (_radius * 0.01), _radius + (_radius * 0.01), dot(dist, dist) * 4.0);',
    '}',
    'void main ()',
    '{',
    '    vec4 texture = texture2D(uMainSampler, outTexCoord);',
    '    float a = min(resolution.x, resolution.y);',
    '	vec2 st = gl_FragCoord.xy / vec2(a, a);',
    '	vec3 color = vec3(circle(st, 0.5));',
    '	gl_FragColor = vec4(color, 1.0);',
    '    /*',
    '    vec2 tc = vec2(outTexCoord.x - 0.5, outTexCoord.y - 0.5);',
    '    float grad = length(tc);',
    '    float circle = smoothstep(0.50, 0.49, grad);',
    '    float ring = circle - smoothstep(width, width - 0.005, grad);',
    '    texture = mix(backgroundColor * backgroundColor.a, texture, texture.a);',
    '    texture = (texture * (circle - ring));',
    '    gl_FragColor = vec4(texture.rgb + (ring * color), texture.a);',
    '    */',
    '}',
].join('\n');
