module.exports = [
    '#define SHADER_NAME PHASER_MULTI_VS',
    'precision mediump float;',
    'uniform mat4 uProjectionMatrix;',
    'uniform int uRoundPixels;',
    'uniform vec2 uResolution;',
    'attribute vec2 inPosition;',
    'attribute vec2 inTexCoord;',
    'attribute float inTexId;',
    'attribute float inTintEffect;',
    'attribute vec4 inTint;',
    'varying vec2 outTexCoord;',
    'varying float outTexId;',
    'varying float outTintEffect;',
    'varying vec4 outTint;',
    'vec2 roundPixels (vec2 position, vec2 targetSize)',
    '{',
    '    return (floor((position * 0.5 + 0.5) * targetSize) / targetSize) * 2.0 - 1.0;',
    '}',
    'void main ()',
    '{',
    '    gl_Position = uProjectionMatrix * vec4(inPosition, 1.0, 1.0);',
    '    if (uRoundPixels == 1)',
    '    {',
    '        gl_Position.xy = roundPixels(gl_Position.xy, uResolution);',
    '    }',
    '    outTexCoord = inTexCoord;',
    '    outTexId = inTexId;',
    '    outTint = inTint;',
    '    outTintEffect = inTintEffect;',
    '}',
].join('\n');
