module.exports = [
    '#pragma phaserTemplate(shaderName)',
    '#pragma phaserTemplate(extensions)',
    '#pragma phaserTemplate(features)',
    '#ifdef GL_FRAGMENT_PRECISION_HIGH',
    'precision highp float;',
    '#else',
    'precision mediump float;',
    '#endif',
    '#pragma phaserTemplate(vertexDefine)',
    'uniform mat4 uProjectionMatrix;',
    'uniform vec2 uResolution;',
    'uniform vec4 uTileWidthHeightMarginSpacing;',
    'attribute vec2 inPosition;',
    'attribute vec2 inTexCoord;',
    'varying vec2 outTexCoord;',
    'varying vec2 outTileStride;',
    '#pragma phaserTemplate(outVariables)',
    '#pragma phaserTemplate(vertexHeader)',
    'void main ()',
    '{',
    '    gl_Position = uProjectionMatrix * vec4(inPosition, 1.0, 1.0);',
    '    outTexCoord = inTexCoord;',
    '    outTileStride = uTileWidthHeightMarginSpacing.xy + uTileWidthHeightMarginSpacing.zz;',
    '    #pragma phaserTemplate(vertexProcess)',
    '}',
].join('\n');
