import Angle from './Angle';
import CenterOn from './CenterOn';
import Clone from './Clone';
import CopyFrom from './CopyFrom';
import Equals from './Equals';
import GetMidPoint from './GetMidPoint';
import GetNormal from './GetNormal';
import GetPointsOnLine from './GetPointsOnLine';
import Height from './Height';
import Length from './Length';
import NormalAngle from './NormalAngle';
import NormalX from './NormalX';
import NormalY from './NormalY';
import PerpSlope from './PerpSlope';
import Random from './Random';
import ReflectAngle from './ReflectAngle';
import Rotate from './Rotate';
import RotateAroundPoint from './RotateAroundPoint';
import RotateAroundXY from './RotateAroundXY';
import SetToAngle from './SetToAngle';
import Slope from './Slope';
import Width from './Width';
export default class Line {
    static Angle: typeof Angle;
    static CenterOn: typeof CenterOn;
    static Clone: typeof Clone;
    static CopyFrom: typeof CopyFrom;
    static Equals: typeof Equals;
    static GetMidPoint: typeof GetMidPoint;
    static GetNormal: typeof GetNormal;
    static GetPointsOnLine: typeof GetPointsOnLine;
    static Height: typeof Height;
    static Length: typeof Length;
    static NormalAngle: typeof NormalAngle;
    static NormalX: typeof NormalX;
    static NormalY: typeof NormalY;
    static PerpSlope: typeof PerpSlope;
    static Random: typeof Random;
    static ReflectAngle: typeof ReflectAngle;
    static Rotate: typeof Rotate;
    static RotateAroundPoint: typeof RotateAroundPoint;
    static RotateAroundXY: typeof RotateAroundXY;
    static SetToAngle: typeof SetToAngle;
    static Slope: typeof Slope;
    static Width: typeof Width;
    x1: any;
    y1: any;
    x2: any;
    y2: any;
    constructor(x1: any, y1: any, x2: any, y2: any);
    setTo(x1: any, y1: any, x2: any, y2: any): this;
    left: number;
    right: number;
    top: number;
    bottom: number;
}
