module.exports = [
    '#ifdef USE_SKINNING',
    '',
    '    mat4 boneMatX = getBoneMatrix( skinIndex.x );',
    '    mat4 boneMatY = getBoneMatrix( skinIndex.y );',
    '    mat4 boneMatZ = getBoneMatrix( skinIndex.z );',
    '    mat4 boneMatW = getBoneMatrix( skinIndex.w );',
    '',
    '    vec4 skinVertex = bindMatrix * vec4(transformed, 1.0);',
    '',
    '    vec4 skinned = vec4( 0.0 );',
    '	skinned += boneMatX * skinVertex * skinWeight.x;',
    '	skinned += boneMatY * skinVertex * skinWeight.y;',
    '	skinned += boneMatZ * skinVertex * skinWeight.z;',
    '	skinned += boneMatW * skinVertex * skinWeight.w;',
    '	skinned = bindMatrixInverse * skinned;',
    '',
    '    transformed = skinned.xyz / skinned.w;',
    '',
    '#endif'
].join('\n');
