import Add from './Add';
import Ceil from './Ceil';
import Clone from './Clone';
import CopyFrom from './CopyFrom';
import Cross from './Cross';
import Divide from './Divide';
import Dot from './Dot';
import Equals from './Equals';
import Floor from './Floor';
import GetCentroid from './GetCentroid';
import GetMagnitude from './GetMagnitude';
import GetMagnitudeSq from './GetMagnitudeSq';
import GetRectangleFromPoints from './GetRectangleFromPoints';
import Interpolate from './Interpolate';
import Invert from './Invert';
import Multiply from './Multiply';
import Negative from './Negative';
import Normalize from './Normalize';
import NormalizeRightHand from './NormalizeRightHand';
import Perp from './Perp';
import Project from './Project';
import ProjectUnit from './ProjectUnit';
import RPerp from './RPerp';
import SetMagnitude from './SetMagnitude';
import Subtract from './Subtract';
export default class Point {
    static Add: typeof Add;
    static Ceil: typeof Ceil;
    static Clone: typeof Clone;
    static CopyFrom: typeof CopyFrom;
    static Cross: typeof Cross;
    static Divide: typeof Divide;
    static Dot: typeof Dot;
    static Equals: typeof Equals;
    static Floor: typeof Floor;
    static GetCentroid: typeof GetCentroid;
    static GetMagnitude: typeof GetMagnitude;
    static GetMagnitudeSq: typeof GetMagnitudeSq;
    static GetRectangleFromPoints: typeof GetRectangleFromPoints;
    static Interpolate: typeof Interpolate;
    static Invert: typeof Invert;
    static Multiply: typeof Multiply;
    static Negative: typeof Negative;
    static Normalize: typeof Normalize;
    static NormalizeRightHand: typeof NormalizeRightHand;
    static Perp: typeof Perp;
    static Project: typeof Project;
    static ProjectUnit: typeof ProjectUnit;
    static RPerp: typeof RPerp;
    static SetMagnitude: typeof SetMagnitude;
    static Subtract: typeof Subtract;
    x: number;
    y: number;
    constructor(x?: number, y?: number);
    setTo(x?: number, y?: number): Point;
}
