import Loader from './systems/Loader';
import MainLoop from './systems/MainLoop';
import UpdateManager from './systems/UpdateManager';
import * as Component from '../components';
import Camera from '../camera/Camera';
export default class Systems {
    state: any;
    config: any;
    events: any;
    textures: any;
    add: any;
    make: any;
    input: any;
    load: Loader;
    tweens: any;
    mainloop: MainLoop;
    updates: UpdateManager;
    camera: Camera;
    children: any;
    color: Component.Color;
    data: any;
    fbo: any;
    time: any;
    transform: any;
    constructor(state: any, config?: any);
    init(): void;
    begin(timestamp: any, frameDelta: any): void;
    update(timestep: any, physicsStep: any): void;
    preRender(): void;
    end(fps: any, panic: any): void;
}
