declare var _default: {
    desktop: boolean;
    webApp: boolean;
    iOS: boolean;
    iOSVersion: number;
    iPhone: boolean;
    iPad: boolean;
    cocoonJS: boolean;
    cocoonJSApp: boolean;
    cordova: boolean;
    node: boolean;
    nodeWebkit: boolean;
    electron: boolean;
    ejecta: boolean;
    crosswalk: boolean;
    android: boolean;
    chromeOS: boolean;
    linux: boolean;
    macOS: boolean;
    windows: boolean;
    windowsPhone: boolean;
    vita: boolean;
    kindle: boolean;
    pixelRatio: number;
};
export default _default;
